### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by ihartaras** [simonedegiacomi/gphotosuploader#21]
Hi, thank for tool!

but I can't run it after installation on ubuntu server 16.04 LTS ( go version go1.10.1 ) 

every time after "go run main.go ... (with any arguments)" I get this errors:

```
# command-line-arguments
./main.go:46:50: undefined: version
./main.go:46:59: undefined: versionDate
```

maybe I missed something

**Comment by simonedegiacomi** [comment]
It's because the main.go file uses two constants declared on version.go. To run a program which depends on other files on the same folder you need to specify all the files. So: go run main.go version.go.

This is inconvenient, so i moved (https://github.com/simonedegiacomi/gphotosuploader/commit/b5eaf1a8a1673aca4c2921b14e8a0e8f38151e76) the version file in a version folder. You should now be able to run the tool with: go run main.go

**Comment by ihartaras** [comment]
Thanks a lot!
